ViewModels/PasswordChangeViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace AspNetCoreIdentityApp.ViewModels
{
    public class PasswordChangeViewModel
    {
        [DataType(DataType.Password)]
        [Required(ErrorMessage = "Lütfen eski şifrenizi giriniz.")]
        [Display(Name = "Şifreniz: ")]
        [MinLength(8,ErrorMessage ="Eski şifreniz en az 8 karakter olmak zorundadır")]
        public string OldPassword { get; set; }

        [DataType(DataType.Password)]
        [Required(ErrorMessage = "Lütfen yeni bir şifre giriniz.")]
        [MinLength(8, ErrorMessage = "Yeni şifreniz en az 8 karakter olmak zorundadır")]
        [Display(Name = "Yeni Şifreniz: ")]
        public string NewPassword { get; set; }

        [DataType(DataType.Password)]
        [Compare(nameof(NewPassword), ErrorMessage = "Şifreler uyumsuz")]
        [Required(ErrorMessage = "Lütfen yeni şifrenizin tekrarını giriniz.")]
        [MinLength(8, ErrorMessage = "Yeni şifreniz en az 8 karakter olmak zorundadır")]
        [Display(Name = "Yeni Şifre Tekrar: ")]
        public string NewPasswordConfirm { get; set; }
    }
}

ViewModels/UserEditViewModel.cs
using AspNetCoreIdentityApp.Models;
using System.ComponentModel.DataAnnotations;

namespace AspNetCoreIdentityApp.ViewModels
{
    public class UserEditViewModel
    {
        [Required(ErrorMessage = "Kullanıcı adı boş bırakılamaz.")]
        [Display(Name = "Kullanıcı Adı: ")]
        public string UserName { get; set; }

        [DataType(DataType.EmailAddress)]
        [EmailAddress(ErrorMessage = "Lütfen geçerli bir email giriniz.")]
        [Required(ErrorMessage = "Email alanı boş bırakılamaz.")]
        [Display(Name = "Email: ")]
        public string Email { get; set; }

        [DataType(DataType.PhoneNumber)]
        [Required(ErrorMessage = "Telefon alanı boş bırakılamaz.")]
        [Display(Name = "Telefon: ")]
        [RegularExpression(@"^\+?\d{1,3}?[-.\s]?\(?\d{3}\)?[-.\s]?\d{3}[-.\s]?\d{4}$", ErrorMessage = "Geçerli bir telefon numarası giriniz.")] //regex
        public string Phone { get; set; }

        [DataType(DataType.Date, ErrorMessage = "Geçersiz tarih formatı.")]
        [Display(Name = "Doğum Tarihi")]
        [DisplayFormat(ApplyFormatInEditMode = false, DataFormatString = "{0:dd/MM/yyyy}", NullDisplayText = "Tarih bilgisi yok.")]
        public DateTime DateOfBirth { get; set; }

        [StringLength(50, ErrorMessage = "Şehir alanı en fazla 50 karakter olabilir.")]
        [RegularExpression(@"^[a-zA-ZğüşıöçĞÜŞİÖÇ\s]+$", ErrorMessage = "Şehir alanı sadece harf ve boşluk içerebilir.")]
        public string City { get; set; }

        [Display(Name = "Profil Resmi")]
        public IFormFile Picture { get; set; }

        [Display(Name = "Cinsiyet")]
        public Gender Gender { get; set; }
    }
}

Controllers/MemberController.cs
using AspNetCoreIdentityApp.Extensions;
using AspNetCoreIdentityApp.Models;
using AspNetCoreIdentityApp.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Extensions.FileProviders;
using System.IO;

namespace AspNetCoreIdentityApp.Controllers
{
    [Authorize]
    public class MemberController : Controller
    {
        private readonly SignInManager<AppUser> _signInManager;
        private readonly UserManager<AppUser> _userManager;
        private readonly IFileProvider _fileProvider;

        public MemberController(SignInManager<AppUser> signInManager, UserManager<AppUser> userManager, IFileProvider fileProvider)
        {
            _signInManager = signInManager;
            _userManager = userManager;
            _fileProvider = fileProvider;
        }

        public async Task<IActionResult> Index()
        {
            var currentUser = await _userManager.FindByNameAsync(User.Identity.Name);

            var userViewModel = new UserViewModel
            {
                UserName = currentUser.UserName,
                Email = currentUser.Email,
                PhoneNumber = currentUser.PhoneNumber,
                PictureURL = currentUser.Picture
            };

            return View(userViewModel);
        }







        public async Task Logout()
        {
            await _signInManager.SignOutAsync();
        }







        [HttpGet]
        public IActionResult PasswordChange()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> PasswordChange(PasswordChangeViewModel request)
        {
            if (!ModelState.IsValid)
            {
                return View();
            }

            var currentUser = await _userManager.FindByNameAsync(User.Identity.Name);
            var checkOldPassword = await _userManager.CheckPasswordAsync(currentUser, request.OldPassword);

            if (checkOldPassword == false)
            {
                ModelState.AddModelError(string.Empty, "Eski şifrenizi yanlış girdiniz.");
                return View();
            }

            if (request.OldPassword == request.NewPassword)
            {
                ModelState.AddModelError(string.Empty, "Yeni şifreniz eski şifrenizle aynı olamaz.");
                return View();
            }

            var changePasswordResult = await _userManager.ChangePasswordAsync(currentUser, request.OldPassword, request.NewPassword);

            if (!changePasswordResult.Succeeded)
            {
                ModelState.AddModelErrorList(changePasswordResult.Errors);
                return View();
            }

            //Şifre değiştirdikten sonra cookie yenilenmesi için kullanıcıya girdi çıktı yaptırıyoruz.
            await _userManager.UpdateSecurityStampAsync(currentUser);
            await _signInManager.SignOutAsync();
            await _signInManager.PasswordSignInAsync(currentUser, request.NewPassword, true, true);


            TempData["PasswordChangeSucceedMessage"] = "Şifreniz Başarıyla Güncellenmiştir.";


            return View();
        }






        [HttpGet]
        public async Task<IActionResult> UserEdit()
        {
            ViewBag.genderList = new SelectList(Enum.GetNames(typeof(Gender)));

            var currentUser = await _userManager.FindByNameAsync(User.Identity.Name);
            var userEditViewModel = new UserEditViewModel()
            {
                UserName = currentUser.UserName,
                Email = currentUser.Email,
                Phone = currentUser.PhoneNumber,
                City = currentUser.City,
                DateOfBirth = currentUser.DateOfBirth,
                Gender = currentUser.Gender
            };

            return View(userEditViewModel);
        }

        [HttpPost]
        public async Task<IActionResult> UserEdit(UserEditViewModel request)
        {
            if (!ModelState.IsValid)
            {
                return View();
            }

            //giriş yapan kullanıcıyı bul
            var currentUser = await _userManager.FindByNameAsync(User.Identity.Name);

            //requestten yani kullanıcının talebinden gelen verileri aşağıdakilerle değiştir.
            currentUser.UserName = request.UserName;
            currentUser.Email = request.Email;
            currentUser.PhoneNumber = request.Phone;
            currentUser.City = request.City;
            currentUser.DateOfBirth = request.DateOfBirth;
            currentUser.Gender = request.Gender;


            if (request.Picture != null && request.Picture.Length > 0)
            {
                var wwwroot = _fileProvider.GetDirectoryContents("wwwroot");
                var randomFileName = $"{Guid.NewGuid()}{Path.GetExtension(request.Picture.FileName)}"; // .jpg .png vs vs. / NewGuid().ToString() kaldırıldı sorun çıkarsa ekle
                var newPicturePath = Path.Combine(wwwroot.First(a => a.Name == "userpictures").PhysicalPath, randomFileName);

                using var stream = new FileStream(newPicturePath, FileMode.Create);

                await request.Picture.CopyToAsync(stream);

                currentUser.Picture = randomFileName;
            }

            var userUpdateResult = await _userManager.UpdateAsync(currentUser);

            if (!userUpdateResult.Succeeded)
            {
                ModelState.AddModelErrorList(userUpdateResult.Errors);
                return View();
            }

            await _userManager.UpdateSecurityStampAsync(currentUser);
            await _signInManager.SignOutAsync();
            await _signInManager.SignInAsync(currentUser, true);


            TempData["UserEditSucceedMessage"] = "Bilgileriniz Başarıyla Güncellenmiştir.";

            var userEditViewModel = new UserEditViewModel()
            {
                UserName = currentUser.UserName,
                Email = currentUser.Email,
                Phone = currentUser.PhoneNumber,
                City = currentUser.City,
                DateOfBirth = currentUser.DateOfBirth,
                Gender = currentUser.Gender,
            };

            return View(userEditViewModel);
        }

        [HttpGet]
        public async Task<IActionResult> AccessDenied(string ReturnURL)
        {
            string message = string.Empty;
            string message2 = string.Empty;

            message = "Bu Sayfayı Görmek İçin Yetkiniz Yok !";
            message2 = "Yetkilendirme için lütfen yöneticiniz ile görüşünüz.";

            ViewBag.message = message;
            ViewBag.message2 = message2;

            return View();
        }
    }
}

Views/Member/AccessDenied.cshtml
@{
    ViewData["Title"] = "AccessDenied";
}

<div class="alert alert-dark mt-5">
    <h1 class="text-center">@ViewBag.message</h1>
    <h1 class="text-center">@ViewBag.message2</h1>
</div>

Views/Member/Index.cshtml
@model UserViewModel
@{
    ViewData["Title"] = "Index";
}
<h1 class="text-center mb-5">Kullanıcı Bilgileri</h1>

<div class="row">
    <div class="col-md-4 offset-md-4 d-flex justify-content-center align-content-center">

        @*TagHelpers klasörünün altında yazmış olduğumuz UserPictureThumbnailTagHelper adlı tag helper*@
        <user-picture-thumbnail picture-url="@Model.PictureURL" class="rounded" width="150"></user-picture-thumbnail>



        @*ESKİ YÖNTEM*@
        @*@if (string.IsNullOrEmpty(Model.PictureURL))
        {
        <img class="rounded" width="150" src="/userpictures/default_profile_picture.png" />
        }
        else
        {
        <img class="rounded" width="150" src="/userpictures/@(Model.PictureURL)" />
        }*@
    </div>
</div>

<div class="table-responsive mt-5">
    <table class="table table-striped table-bordered">
        <thead class="thead-dark">
            <tr>
                <th scope="col">Kullanıcı Adı</th>
                <th scope="col">Email</th>
                <th scope="col">Telefon</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>@Model.UserName</td>
                <td>@Model.Email</td>
                <td>@Model.PhoneNumber</td>
            </tr>
        </tbody>
    </table>
</div>

Views/Member/PasswordChange.cshtml
@model PasswordChangeViewModel
@{
    ViewData["Title"] = "PasswordChange";
}

@section Scripts
    {
    @await Html.PartialAsync("_ValidationScriptsPartial")
}




<div class="row">
    <div class="col-md-6 offset-md-3">
        <h2 class="mb-5 text-center">Şifre Değiştir</h2>

        @if (TempData["PasswordChangeSucceedMessage"] != null)
        {
            <div class="alert alert-success" role="alert">
                @TempData["PasswordChangeSucceedMessage"]
            </div>
        }

        <div asp-validation-summary=ModelOnly class="alert alert-danger" role="alert"></div>

        <form asp-controller="Member" asp-action="PasswordChange" method="post">
            <div class="mb-3">
                <label for="OldPassword" class="form-label" asp-for="OldPassword"></label>
                <input asp-for="OldPassword" class="form-control">
                <span class="text-danger" asp-validation-for="OldPassword"></span>
            </div>

            <div class="mb-3">
                <label for="NewPassword" class="form-label" asp-for="NewPassword"></label>
                <input asp-for="NewPassword" class="form-control">
                <span class="text-danger" asp-validation-for="NewPassword"></span>
            </div>

            <div class="mb-3">
                <label for="NewPasswordConfirm" class="form-label" asp-for="NewPasswordConfirm"></label>
                <input asp-for="NewPasswordConfirm" class="form-control">
                <span class="text-danger" asp-validation-for="NewPasswordConfirm"></span>
            </div>

            <div class="row justify-content-end">
                <div class="col-auto">
                    <button type="submit" class="btn btn-primary">Şifreyi Güncelle</button>
                </div>
            </div>
        </form>
    </div>
</div>

Views/Member/UserEdit.cshtml
@model UserEditViewModel
@{
    ViewData["Title"] = "UserEdit";
}

@section Scripts
    {
    @await Html.PartialAsync("_ValidationScriptsPartial")
}




<div class="row">
    <div class="col-md-6 offset-md-3">
        <h2 class="mb-5 text-center">Hesap Bilgileri Güncelle</h2>

        @if (TempData["UserEditSucceedMessage"] != null)
        {
            <div class="alert alert-success" role="alert">
                @TempData["UserEditSucceedMessage"]
            </div>
        }

        <div asp-validation-summary=ModelOnly class="alert alert-danger" role="alert"></div>

        <form asp-controller="Member" asp-action="UserEdit" method="post" enctype="multipart/form-data">
            <div class="mb-3">
                <label for="UserName" class="form-label" asp-for="UserName"></label>
                <input asp-for="UserName" class="form-control">
                <span class="text-danger" asp-validation-for="UserName"></span>
            </div>

            <div class="mb-3">
                <label for="Email" class="form-label" asp-for="Email"></label>
                <input asp-for="Email" class="form-control">
                <span class="text-danger" asp-validation-for="Email"></span>
            </div>

            <div class="mb-3">
                <label for="Phone" class="form-label" asp-for="Phone"></label>
                <input asp-for="Phone" class="form-control">
                <span class="text-danger" asp-validation-for="Phone"></span>
            </div>

            <div class="mb-3">
                <label for="DateOfBirth" class="form-label" asp-for="DateOfBirth"></label>
                <input asp-for="DateOfBirth" class="form-control" type="date">
                <span class="text-danger" asp-validation-for="DateOfBirth"></span>
            </div>

            <div class="mb-3">
                <label for="City" class="form-label" asp-for="City"></label>
                <input asp-for="City" class="form-control">
                <span class="text-danger" asp-validation-for="City"></span>
            </div>


            <div class="mb-3">
                <label for="Gender" class="form-label" asp-for="Gender"></label>
                <select class="form-control" asp-for="Gender" asp-items="ViewBag.genderList">
                    <option value="" disabled selected>Cinsiyet Seçiniz</option>
                </select>
                <span class="text-danger" asp-validation-for="Gender"></span>
            </div>

            <div class="mb-3">
                <label for="Picture" class="form-label" asp-for="Picture"></label>
                <input asp-for="Picture" class="form-control" type="file">
                <span class="text-danger" asp-validation-for="Picture"></span>
            </div>

            <div class="row justify-content-end">
                <div class="col-auto">
                    <button type="submit" class="btn btn-primary">Bilgileri Güncelle</button>
                </div>
            </div>
        </form>
    </div>
</div>