Areas/Admin/ViewModels/AssingRoleViewModel.cs
namespace AspNetCoreIdentityApp.Areas.Admin.ViewModels
{
    public class AssingRoleViewModel
    {
        public string RoleID { get; set; }
        public string RoleName { get; set; }
        public bool Exist { get; set; }
    }
}

Areas/Admin/ViewModels/CreateRoleViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace AspNetCoreIdentityApp.Areas.Admin.ViewModels
{
    public class CreateRoleViewModel
    {
        [Required(ErrorMessage = "Lütfen bir ünvan adı girin.")]
        [StringLength(40, MinimumLength = 3, ErrorMessage = "Ünvan adı min. {2} maks. {1} karakter olabilir.")]
        public string RoleName { get; set; }
    }
}

Areas/Admin/ViewModels/RoleViewModel.cs
namespace AspNetCoreIdentityApp.Areas.Admin.ViewModels
{
    public class RoleViewModel
    {
        public string RoleID { get; set; }
        public string RoleName { get; set; }
    }
}

Areas/Admin/ViewModels/UpdateRoleViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace AspNetCoreIdentityApp.Areas.Admin.ViewModels
{
    public class UpdateRoleViewModel
    {
        public string RoleID { get; set; }

        [Required(ErrorMessage = "Lütfen bir ünvan adı girin.")]
        [StringLength(40, MinimumLength = 5, ErrorMessage = "Ünvan adı min. {2} maks. {1} karakter olabilir.")]
        public string RoleName { get; set; }
    }
}

Areas/Admin/Controllers/RolesController.cs
using AspNetCoreIdentityApp.Areas.Admin.ViewModels;
using AspNetCoreIdentityApp.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using AspNetCoreIdentityApp.Extensions;
using Microsoft.EntityFrameworkCore;
using Azure.Core;
using Microsoft.AspNetCore.Authorization;

namespace AspNetCoreIdentityApp.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class RolesController : Controller
    {
        private readonly UserManager<AppUser> _userManager;
        private readonly RoleManager<AppRole> _roleManager;

        public RolesController(UserManager<AppUser> userManager, RoleManager<AppRole> roleManager)
        {
            _userManager = userManager;
            _roleManager = roleManager;
        }

        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Index()
        {
            var roles = await _roleManager.Roles.Select(a => new RoleViewModel()
            {
                RoleID = a.Id,
                RoleName = a.Name
            }).ToListAsync();

            return View(roles);
        }






        [Authorize(Roles = "Admin")]
        [HttpGet]
        public IActionResult CreateRole()
        {
            return View();
        }

        [Authorize(Roles = "Admin")]
        [HttpPost]
        public async Task<IActionResult> CreateRole(CreateRoleViewModel request)
        {
            var result = await _roleManager.CreateAsync(new AppRole() { Name = request.RoleName });

            if (!result.Succeeded)
            {
                ModelState.AddModelErrorList(result.Errors);
                return View();
            }

            TempData["SucceededMessage"] = "Ünvan Başarıyla Eklenmiştir.";

            return RedirectToAction(nameof(RolesController.Index));
        }








        [Authorize(Roles = "Admin")]
        [HttpGet]
        public async Task<IActionResult> UpdateRole(string id)
        {
            var roleToUpdate = await _roleManager.FindByIdAsync(id);

            if (roleToUpdate == null)
            {
                throw new Exception("Ünvan Bulunamamıştır");
            }


            return View(new UpdateRoleViewModel()
            {
                RoleID = roleToUpdate.Id,
                RoleName = roleToUpdate.Name
            });
        }

        [Authorize(Roles = "Admin")]
        [HttpPost]
        public async Task<IActionResult> UpdateRole(UpdateRoleViewModel request)
        {
            var roleToUpdate = await _roleManager.FindByIdAsync(request.RoleID);

            if (roleToUpdate == null)
            {
                throw new Exception("Ünvan Bulunamamıştır");
            }

            roleToUpdate.Name = request.RoleName;

            await _roleManager.UpdateAsync(roleToUpdate);

            TempData["SucceededMessage"] = "Ünvan Başarıyla Güncellenmiştir.";

            return View();
        }






        [Authorize(Roles = "Admin")]
        [HttpGet]
        public async Task<IActionResult> DeleteRole(string id)
        {
            var roleToDelete = await _roleManager.FindByIdAsync(id);


            if (roleToDelete == null)
            {
                throw new Exception("Ünvan Bulunamamıştır");
            }

           var result = await _roleManager.DeleteAsync(roleToDelete);

            if (!result.Succeeded)
            {
                throw new Exception(result.Errors.Select(a => a.Description).First());
            }

            TempData["SucceededMessage"] = "Ünvan Başarıyla Silinmiştir.";

            return RedirectToAction(nameof(RolesController.Index));
        }





        [Authorize(Roles = "Admin")]
        [HttpGet]
        public async Task<IActionResult> AssingRole(string id)
        {
            var currentUser = await _userManager.FindByIdAsync(id);
            ViewBag.userid = id;

            var roles = await _roleManager.Roles.ToListAsync();
            var roleViewModelList = new List<AssingRoleViewModel>();
            var userRoles = await _userManager.GetRolesAsync(currentUser);

            foreach (var role in roles)
            {
                var assingRoleViewModel = new AssingRoleViewModel() 
                {
                    RoleID = role.Id,
                    RoleName = role.Name
                };


                if (userRoles.Contains(role.Name))
                {
                    assingRoleViewModel.Exist = true;
                }

                roleViewModelList.Add(assingRoleViewModel);
            }

            
            return View(roleViewModelList);
        }

        [Authorize(Roles = "Admin")]
        [HttpPost]
        public async Task<IActionResult> AssingRole(string id ,List<AssingRoleViewModel> requestList)
        {
            var user = await _userManager.FindByIdAsync(id);

            foreach (var role in requestList)
            {
                if (role.Exist)
                {
                    await _userManager.AddToRoleAsync(user, role.RoleName);
                }
                else
                {
                    await _userManager.RemoveFromRoleAsync(user, role.RoleName);
                }
            }


            return RedirectToAction(nameof(HomeController.UserList),"Home");
        }
    }
}

Areas/Admin/Views/Roles/AssingRole.cshtml
@model List<AssingRoleViewModel>
@{
    ViewData["Title"] = "AssingRole";
}

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <div class="card">
                <div class="card-body">
                    <h1 class="card-title text-center mb-4">Ünvan Atama</h1>

                    @if (TempData["SucceededMessage"] != null)
                    {
                        <div class="alert alert-success" role="alert">
                            @TempData["SucceededMessage"]
                        </div>
                    }

                    <form asp-controller="Roles" asp-action="AssingRole" asp-route-userid="@ViewBag.userid" method="post">
                        @for (int i = 0; i < Model.Count; i++)
                        {
                            <div class="mb-3 form-check">
                                <input type="checkbox" class="form-check-input" asp-for="@Model[i].Exist">
                                <label class="form-check-label" for="exampleCheck1">@Model[i].RoleName</label>
                                <input type="hidden" asp-for="@Model[i].RoleName" />
                                <input type="hidden" asp-for="@Model[i].RoleID" />
                            </div>
                        }

                        <div class="d-grid gap-2">
                            <button type="submit" class="btn btn-primary">Ünvan Ata</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>

    <div class="row justify-content-center mt-3">
        <div class="col-md-6">
            <div class="d-grid gap-2">
                <a asp-action="Index" class="btn btn-secondary">Ünvan Listesi</a>
                <a asp-controller="Home" asp-action="UserList" class="btn btn-secondary">Kullanıcı Listesi</a>
            </div>
        </div>
    </div>
</div>

Areas/Admin/Views/Roles/CreateRole.cshtml
@model CreateRoleViewModel

@{
    ViewData["Title"] = "CreateRole";
}
@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <div class="card">
                <div class="card-body">
                    <h1 class="card-title text-center mb-4">Ünvan Ekleme</h1>

                    @if (TempData["SucceededMessage"] != null)
                    {
                        <div class="alert alert-success" role="alert">
                            @TempData["SucceededMessage"]
                        </div>
                    }

                    <form asp-controller="Roles" asp-action="CreateRole" method="post">
                        <div asp-validation-summary="ModelOnly" class="text-danger"></div>

                        <div class="mb-3">
                            <label for="RoleName" class="form-label">Ünvan adı</label>
                            <input asp-for="RoleName" class="form-control" id="RoleName" placeholder="Ünvan adı" />
                            <span asp-validation-for="RoleName" class="text-danger"></span>
                        </div>

                        <div class="d-grid gap-2">
                            <button type="submit" class="btn btn-primary">Ekle</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>

    <div class="row justify-content-center mt-3">
        <div class="col-md-6">
            <div class="d-grid gap-2">
                <a asp-action="Index" class="btn btn-secondary">Ünvan Listesi</a>
            </div>
        </div>
    </div>
</div>

Areas/Admin/Views/Roles/Index.cshtml
@model List<RoleViewModel>
@{
    ViewData["Title"] = "Index";
}



<div class="container">
    <div class="row">

        <div class="col-md-12 mb-4">
            <div class="d-flex justify-content-between align-items-center">
                <h1 class="mb-0">ÜNVAN LİSTESİ</h1>
                <a asp-controller="Roles" asp-action="CreateRole" asp-area="Admin" class="btn btn-success mb-3">Ünvan Ekle</a>
            </div>
        </div>

        <div class="col-md-12 align-middle" style="text-align:center;">

            @if (TempData["SucceededMessage"] != null)
            {
                <div class="alert alert-success" role="alert">
                    @TempData["SucceededMessage"]
                </div>
            }

            <div class="table-responsive">
                <table class="table table-hover">
                    <thead class="thead-dark">
                        <tr>
                            <th>ID</th>
                            <th>ÜNVAN ADI</th>
                            <th></th>
                        </tr>
                    </thead>

                    <tbody>
                        @foreach (var role in Model)
                        {
                            <tr>
                                <td class="align-middle">@role.RoleID</td>
                                <td class="align-middle">@role.RoleName</td>
                                <td class="align-middle">
                                    <a asp-controller="Roles" asp-action="UpdateRole" asp-area="Admin" asp-route-id="@role.RoleID" class="btn btn-sm btn-warning">Güncelle</a>
                                    <a asp-controller="Roles" asp-action="DeleteRole" asp-area="Admin" asp-route-id="@role.RoleID" class="btn btn-sm btn-danger my-1">Sil</a>
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

Areas/Admin/Views/Roles/UpdateRole.cshtml
@model UpdateRoleViewModel
@{
    ViewData["Title"] = "UpdateRole";
}

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <div class="card">
                <div class="card-body">
                    <h1 class="card-title text-center mb-4">Ünvan Düzenleme</h1>

                    @if (TempData["SucceededMessage"] != null)
                    {
                        <div class="alert alert-success" role="alert">
                            @TempData["SucceededMessage"]
                        </div>
                    }

                    <form asp-controller="Roles" asp-action="UpdateRole" method="post">
                        <div asp-validation-summary="ModelOnly" class="text-danger"></div>

                        <input type="hidden" asp-for="RoleID" />

                        <div class="mb-3">
                            <label asp-for="RoleName" class="form-label">Ünvan Adı</label>
                            <input asp-for="RoleName" class="form-control" />
                            <span asp-validation-for="RoleName" class="text-danger"></span>
                        </div>

                        <div class="d-grid gap-2">
                            <button type="submit" class="btn btn-primary">Güncelle</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>

    <div class="row justify-content-center mt-3">
        <div class="col-md-6">
            <div class="d-grid gap-2">
                <a asp-action="Index" class="btn btn-secondary">Ünvan Listesi</a>
            </div>
        </div>
    </div>
</div>